---
repos:
- repo: https://github.com/python-poetry/poetry
  rev: "1.8.4"
  hooks:
  - id: poetry-check
  - id: poetry-lock

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.4
  hooks:
  - id: ruff
  - id: ruff-format

- repo: local
  hooks:
  - id: requirement.txt
    name: requirement.txt
    entry: ./scripts/requirements.sh
    files: poetry.lock
    language: system
